# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syringe_pump.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='syringe_pump.proto',
  package='syringe_pump',
  syntax='proto3',
  serialized_pb=_b('\n\x12syringe_pump.proto\x12\x0csyringe_pump\x1a\x1bgoogle/protobuf/empty.proto\"z\n\x0bInstruction\x12\x10\n\x06infuse\x18\x01 \x01(\x08H\x00\x12\x12\n\x08withdraw\x18\x02 \x01(\x08H\x00\x12\x0c\n\x04rate\x18\x03 \x01(\t\x12\x0e\n\x06volume\x18\x04 \x01(\t\x12\x0c\n\x04time\x18\x05 \x01(\t\x12\x0c\n\x04stop\x18\x06 \x01(\x08\x42\x0b\n\tdirection\"\xeb\x02\n\x06Status\x12\x10\n\x06infuse\x18\x01 \x01(\x08H\x00\x12\x12\n\x08withdraw\x18\x02 \x01(\x08H\x00\x12\x0c\n\x04rate\x18\x03 \x01(\t\x12\x0e\n\x06volume\x18\x04 \x01(\t\x12\x16\n\x0etime_remaining\x18\x05 \x01(\t\x12\'\n\x04make\x18\x06 \x01(\x0b\x32\x19.syringe_pump.Status.Make\x12\x32\n\x05motor\x18\x07 \x01(\x0b\x32#.syringe_pump.Status.MotorCondition\x1a$\n\x04Make\x12\r\n\x05model\x18\x01 \x01(\t\x12\r\n\x05\x62rand\x18\x02 \x01(\t\x1au\n\x0eMotorCondition\x12\x11\n\x07running\x18\x01 \x01(\x08H\x00\x12\x11\n\x07stopped\x18\x02 \x01(\x08H\x00\x12\x11\n\x07stalled\x18\x04 \x01(\x08H\x00\x12\x11\n\x07no_comm\x18\x05 \x01(\x08H\x00\x12\x0f\n\x07message\x18\x03 \x01(\tB\x06\n\x04typeB\x0b\n\tdirection2\xd7\x01\n\x0bSyringePump\x12\x44\n\x0fSendInstruction\x12\x19.syringe_pump.Instruction\x1a\x14.syringe_pump.Status\"\x00\x12;\n\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x14.syringe_pump.Status\"\x00\x12\x45\n\x11GetStatusStreamed\x12\x16.google.protobuf.Empty\x1a\x14.syringe_pump.Status\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_INSTRUCTION = _descriptor.Descriptor(
  name='Instruction',
  full_name='syringe_pump.Instruction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='infuse', full_name='syringe_pump.Instruction.infuse', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='withdraw', full_name='syringe_pump.Instruction.withdraw', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rate', full_name='syringe_pump.Instruction.rate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='syringe_pump.Instruction.volume', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='syringe_pump.Instruction.time', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop', full_name='syringe_pump.Instruction.stop', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='direction', full_name='syringe_pump.Instruction.direction',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=65,
  serialized_end=187,
)


_STATUS_MAKE = _descriptor.Descriptor(
  name='Make',
  full_name='syringe_pump.Status.Make',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='syringe_pump.Status.Make.model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brand', full_name='syringe_pump.Status.Make.brand', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=421,
)

_STATUS_MOTORCONDITION = _descriptor.Descriptor(
  name='MotorCondition',
  full_name='syringe_pump.Status.MotorCondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='running', full_name='syringe_pump.Status.MotorCondition.running', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stopped', full_name='syringe_pump.Status.MotorCondition.stopped', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stalled', full_name='syringe_pump.Status.MotorCondition.stalled', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='no_comm', full_name='syringe_pump.Status.MotorCondition.no_comm', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='syringe_pump.Status.MotorCondition.message', index=4,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='syringe_pump.Status.MotorCondition.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=423,
  serialized_end=540,
)

_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='syringe_pump.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='infuse', full_name='syringe_pump.Status.infuse', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='withdraw', full_name='syringe_pump.Status.withdraw', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rate', full_name='syringe_pump.Status.rate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='syringe_pump.Status.volume', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_remaining', full_name='syringe_pump.Status.time_remaining', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='make', full_name='syringe_pump.Status.make', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor', full_name='syringe_pump.Status.motor', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STATUS_MAKE, _STATUS_MOTORCONDITION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='direction', full_name='syringe_pump.Status.direction',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=190,
  serialized_end=553,
)

_INSTRUCTION.oneofs_by_name['direction'].fields.append(
  _INSTRUCTION.fields_by_name['infuse'])
_INSTRUCTION.fields_by_name['infuse'].containing_oneof = _INSTRUCTION.oneofs_by_name['direction']
_INSTRUCTION.oneofs_by_name['direction'].fields.append(
  _INSTRUCTION.fields_by_name['withdraw'])
_INSTRUCTION.fields_by_name['withdraw'].containing_oneof = _INSTRUCTION.oneofs_by_name['direction']
_STATUS_MAKE.containing_type = _STATUS
_STATUS_MOTORCONDITION.containing_type = _STATUS
_STATUS_MOTORCONDITION.oneofs_by_name['type'].fields.append(
  _STATUS_MOTORCONDITION.fields_by_name['running'])
_STATUS_MOTORCONDITION.fields_by_name['running'].containing_oneof = _STATUS_MOTORCONDITION.oneofs_by_name['type']
_STATUS_MOTORCONDITION.oneofs_by_name['type'].fields.append(
  _STATUS_MOTORCONDITION.fields_by_name['stopped'])
_STATUS_MOTORCONDITION.fields_by_name['stopped'].containing_oneof = _STATUS_MOTORCONDITION.oneofs_by_name['type']
_STATUS_MOTORCONDITION.oneofs_by_name['type'].fields.append(
  _STATUS_MOTORCONDITION.fields_by_name['stalled'])
_STATUS_MOTORCONDITION.fields_by_name['stalled'].containing_oneof = _STATUS_MOTORCONDITION.oneofs_by_name['type']
_STATUS_MOTORCONDITION.oneofs_by_name['type'].fields.append(
  _STATUS_MOTORCONDITION.fields_by_name['no_comm'])
_STATUS_MOTORCONDITION.fields_by_name['no_comm'].containing_oneof = _STATUS_MOTORCONDITION.oneofs_by_name['type']
_STATUS.fields_by_name['make'].message_type = _STATUS_MAKE
_STATUS.fields_by_name['motor'].message_type = _STATUS_MOTORCONDITION
_STATUS.oneofs_by_name['direction'].fields.append(
  _STATUS.fields_by_name['infuse'])
_STATUS.fields_by_name['infuse'].containing_oneof = _STATUS.oneofs_by_name['direction']
_STATUS.oneofs_by_name['direction'].fields.append(
  _STATUS.fields_by_name['withdraw'])
_STATUS.fields_by_name['withdraw'].containing_oneof = _STATUS.oneofs_by_name['direction']
DESCRIPTOR.message_types_by_name['Instruction'] = _INSTRUCTION
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Instruction = _reflection.GeneratedProtocolMessageType('Instruction', (_message.Message,), dict(
  DESCRIPTOR = _INSTRUCTION,
  __module__ = 'syringe_pump_pb2'
  # @@protoc_insertion_point(class_scope:syringe_pump.Instruction)
  ))
_sym_db.RegisterMessage(Instruction)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(

  Make = _reflection.GeneratedProtocolMessageType('Make', (_message.Message,), dict(
    DESCRIPTOR = _STATUS_MAKE,
    __module__ = 'syringe_pump_pb2'
    # @@protoc_insertion_point(class_scope:syringe_pump.Status.Make)
    ))
  ,

  MotorCondition = _reflection.GeneratedProtocolMessageType('MotorCondition', (_message.Message,), dict(
    DESCRIPTOR = _STATUS_MOTORCONDITION,
    __module__ = 'syringe_pump_pb2'
    # @@protoc_insertion_point(class_scope:syringe_pump.Status.MotorCondition)
    ))
  ,
  DESCRIPTOR = _STATUS,
  __module__ = 'syringe_pump_pb2'
  # @@protoc_insertion_point(class_scope:syringe_pump.Status)
  ))
_sym_db.RegisterMessage(Status)
_sym_db.RegisterMessage(Status.Make)
_sym_db.RegisterMessage(Status.MotorCondition)



_SYRINGEPUMP = _descriptor.ServiceDescriptor(
  name='SyringePump',
  full_name='syringe_pump.SyringePump',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=556,
  serialized_end=771,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendInstruction',
    full_name='syringe_pump.SyringePump.SendInstruction',
    index=0,
    containing_service=None,
    input_type=_INSTRUCTION,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStatus',
    full_name='syringe_pump.SyringePump.GetStatus',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStatusStreamed',
    full_name='syringe_pump.SyringePump.GetStatusStreamed',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_STATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYRINGEPUMP)

DESCRIPTOR.services_by_name['SyringePump'] = _SYRINGEPUMP

# @@protoc_insertion_point(module_scope)
